services:
  - type: web
    name: main
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y libxml2-dev libxslt-dev
      pip install -r requirements.txt
    startCommand: gunicorn server:app